/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("sbp v1.0");

  label1 = new GLabel(this, 445, 535, 51, 38);
  label1.setText("Target");
  label1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label1.setOpaque(true);
  label3 = new GLabel(this, 360, 440, 69, 38);
  label3.setText("NA");
  label3.setTextBold();
  label3.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label3.setOpaque(true);
  label4 = new GLabel(this, 106, 635, 70, 38);
  label4.setText("NA");
  label4.setTextBold();
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(true);
  label5 = new GLabel(this, 358, 635, 70, 38);
  label5.setText("NA");
  label5.setTextBold();
  label5.setLocalColorScheme(GCScheme.RED_SCHEME);
  label5.setOpaque(true);
  label7 = new GLabel(this, 106, 440, 70, 38);
  label7.setText("NA");
  label7.setTextBold();
  label7.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label7.setOpaque(true);
  
 
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GLabel label2; 
GLabel label1; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label7; 
GSlider slider2; 
GSlider slider3; 
GSlider slider4; 
GSlider slider5; 
GSlider slider6; 
GKnob knob1; 
GKnob knob2; 
GKnob knob3; 
GKnob knob4; 
GKnob knob5; 
GLabel label6; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GLabel label11; 
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GOption option1; 
GOption option2; 
GOption option3; 

