/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("sbp v1.0");

  label1 = new GLabel(this, 445, 544, 50, 28);
  label1.setText("...");
  label1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label1.setOpaque(true);

  label2 = new GLabel(this, 191, 544, 50, 28);
  label2.setText("...");
  label2.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label2.setOpaque(true);
  
  label3 = new GLabel(this, 360, 440, 70, 28);
  label3.setText("...");
  label3.setTextBold();
  label3.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label3.setOpaque(true);

  label6 = new GLabel(this, 360, 470, 70, 28);
  label6.setText("...");
  label6.setTextBold();
  label6.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label6.setOpaque(true);
  
  label4 = new GLabel(this, 106, 635, 70, 28);
  label4.setText("...");
  label4.setTextBold();
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(true);
  
  label5 = new GLabel(this, 360, 635, 70, 28);
  label5.setText("...");
  label5.setTextBold();
  label5.setLocalColorScheme(GCScheme.RED_SCHEME);
  label5.setOpaque(true);
  
  label7 = new GLabel(this, 106, 440, 70, 28);
  label7.setText("...");
  label7.setTextBold();
  label7.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label7.setOpaque(true);

  label8 = new GLabel(this, 106, 470, 70, 28);
  label8.setText("...");
  label8.setTextBold();
  label8.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label8.setOpaque(true);  
  
  //label9 = new GLabel(this, 378, 189, 35, 18);
  //label9.setText("...");
  //label9.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  //label9.setOpaque(true);

  //label10 = new GLabel(this, 60, 264, 35, 18);
  //label10.setText("Target");
  //label10.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  //label10.setOpaque(true);

  label11 = new GLabel(this, 370, 324, 75, 18);
  label11.setText("...");
  label11.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label11.setOpaque(true);
  
  label12 = new GLabel(this, 116, 324, 75, 18);
  label12.setText("...");
  label12.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label12.setOpaque(true);

  label13 = new GLabel(this, 258, 189, 155, 18);
  label13.setText("Waiting");
  label13.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label13.setOpaque(true);

 
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GLabel label2; 
GLabel label1; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label7; 
GSlider slider2; 
GSlider slider3; 
GSlider slider4; 
GSlider slider5; 
GSlider slider6; 
GKnob knob1; 
GKnob knob2; 
GKnob knob3; 
GKnob knob4; 
GKnob knob5; 
GLabel label6; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GLabel label11; 
GLabel label12; 
GLabel label13; 
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GOption option1; 
GOption option2; 
GOption option3; 

